version: '3'

services:
  selenium_hub:
    # image: selenium/hub:latest
    image: selenium/hub:3.141.59-antimony
    ports:
      # - "4442:4442"
      # - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=60000
      - GRID_TIMEOUT=90000
      - GRID_MAX_SESSION=50
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120000

  appium_android_device:
    image: appium/appium:latest
    shm_size: 2gb
    depends_on:
      - selenium_hub
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      #- ~/.android:/home/androidusr/.android
    environment:
      - CONNECT_TO_GRID=true
      # - APPIUM_HOST='127.0.0.1'
      # - APPIUM_PORT=4723
      - SELENIUM_HOST=selenium_hub
      - SELENIUM_PORT=4444
      - APPIUM_ADDITIONAL_PARAMS=--base-path /wd/hub
      # Enable it for msite testing
      #- BROWSER_NAME=chrome

