# Working: NO

version: '3'

services:
  android_emulator:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/kvm
    ports:
      - 5555:5555
      - 5554:5554
      - 5037:5037
    privileged: true
    networks:
      - appium_network

  appium_container:
    image: appium/appium
    ports:
      - 4723:4723
    networks:
      - appium_network
    depends_on:
      - android_emulator
    privileged: true

networks:
  appium_network:
    driver: bridge