# Working: NO

version: '3'

services:
  selenium_hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=60000
      - GRID_TIMEOUT=90000
      - GRID_MAX_SESSION=50
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120000

  appium_android_device:
    image: appium/appium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - CONNECT_TO_GRID=true
      - APPIUM_PORT=4723
      - SELENIUM_HOST=selenium-hub
      - APPIUM_ADDITIONAL_PARAMS=--base-path /wd/hub

